name: 'Setup Java JDK'
description: 'Set up a specific version of the Java JDK and add the command-line tools to the PATH'
author: 'GitHub'
inputs: 
  java-version:
    description: 'The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)'
    required: true
  java-package:
    description: 'The package type (jre, jdk, jdk+fx)'
    required: false
    default: 'jdk'
  architecture:
    description: 'The architecture (x86, x64) of the package.'
    required: false
    default: 'x64'
  jdkFile:
    description: 'Path to where the compressed JDK is located. The path could be in your source repository or a local path on the agent.'
    required: false
runs:
  using: 'node12'
  main: 'lib/setup-java.js'
