name: 'Node 12 Template Action'
description: 'Get started with Node actions'
author: 'GitHub'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'node'
  main: 'lib/main.js'